version: "3.7"

services:
  react-frontend:
    container_name: react-frontend
    build:
      context: .
      args:
        API_HOST: http://localhost:5000
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
   
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API=${DOMAIN}