version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: ./frontend/my-app/
      dockerfile: Dockerfile
    volumes:
      - './frontend/my-app/:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true