apiVersion: v1
kind: Service
metadata:
  name: edge-frontend
spec:
  type: NodePort
  selector:
    app: edge-frontend
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 3000
      targetPort: 3000