apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-admin-clusterrole
rules:
- apiGroups: [""]
  resources: ["deployments", "pods", "namespaces"]
  verbs: ["get", "list", "create", "delete"]