apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: deployment-admin-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: model-manager
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: deployment-admin-clusterrole
  apiGroup: ""