apiVersion: v1
kind: Service
metadata:
  name: model-manager
spec:
  type: NodePort
  selector:
    app: model-manager
  ports:
    - protocol: TCP
      nodePort: 32000
      port: 8000
      targetPort: 8000