apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  type: NodePort
  selector:
    app: main-service
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 5000
      targetPort: 5000